language: python
python:
    - '3.6'
install:
  - pip install pipenv
  - pip install -U tox python-coveralls

script:
  - pipenv install --dev
  - pipenv run pip freeze > requirements-tests.txt
  - coverage erase
  - tox
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - a.vara.1986@gmail.com