site_name: PyMS
site_url: https://github.com/python-microservices/pyms
repo_url: https://github.com/python-microservices/pyms
repo_name: GitHub
site_author: Alberto Vara
nav:
    - Home: index.md
    - Installation: installation.md
    - Quickstart: quickstart.md
    - Configuration: configuration.md
    - Services: services.md
    - Microservice class: ms_class.md
    - Routing: routing.md
    - Encrypt/Decrypt Configuration: encrypt_decryt_configuration.md
    - Command line: command_line.md
    - Examples: examples.md
    - PyMS structure: structure.md
    - Structure of a microservice project: structure_project.md
    - Tutorials: tutorials.md
    - External Links and Articles: links_articles.md
    - HacktoberfestES: hacktoberfest_es_2020.md
markdown_extensions:
  - admonition
theme:
  name: 'material'
